#!/bin/bash

# install the packaging/ subdir into a project assumed to be in the CWD

set -e

packaging_dir=${0%/*}
cp -a "$packaging_dir" .
rm -rf packaging/{debian/,.git/,_topdir,utils,.vscode}/
rm -f packaging/{packaging,Jenkinsfile,Makefile,README.md,install,packaging.code-workspace,SECURITY.md,LICENSE}
ln "$packaging_dir"/.git/hooks/* .git/hooks/
